version: '{build}'
image: ubuntu
stack: jdk 8

cache:
  - /home/appveyor/.m2
install:
  - ps: .\build_scripts\UpdateBuildVersion.ps1
before_build:
  - mvn -v
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn install verify
test: off
artifacts:
  - path: "**/target/*.?ar"
    name: "reCloth"
  - path: "**/target/*.exe"
    name: "reCloth"
on_success:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {.\build_scripts\discord-webhook.ps1 success $env:DISCORD_WEBHOOK_URL}
on_failure:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {.\build_scripts\discord-webhook.ps1 failure $env:DISCORD_WEBHOOK_URL}
deploy_script:
  - ps: if ($env:APPVEYOR_REPO_BRANCH -eq "main") {.\build_scripts\trigger-redeploy.ps1}
